### ISSUE TITLE
Can't join the IRC

### ISSUE THREAD

**Issue by muazamkamal** [ineentho/mcfm-tools#1]
After following all the steps and getting the API key. When entering the command line `mcfm -u Ineentho -o oauth:7j8vge4o0l1js2m1z6gb936cpwhmm1`, replacing the username and key, pressing enter didn't do anything. Did I did something wrong? 
![untitled-1](https://cloud.githubusercontent.com/assets/5335874/13034249/5f01f07e-d36b-11e5-921d-24acd15a6b62.png)

**Comment by ineentho** [comment]
To be honest I've not been using this in a long time. I'll check if it still is working when I come home in a few hours.

**Comment by ineentho** [comment]
It does still work for me. I believe that nothing = incorrect login details, though I really should've put an error message there.

**Comment by muazamkamal** [comment]
I tried deauthorizing and request another key, though it still wouldn't work. Any idea on what I did wrong?

**Comment by ineentho** [comment]
Apparently they changed the message you get when you log in with wrong credentials, so now it will probably display Login unsuccessful at least.

Maybe it's the source of the token that is the problem, I've been using https://twitchtools.com/chat-token instead, although I'm not sure how that possibly could be the difference.

I actually thought about rewriting this so that you don't have to log in when Twitch released their html5 chat, maybe I should look into that again.

**Comment by muazamkamal** [comment]
Just tried the source for token you gave (https://twitchtools.com/chat-token), as you said, no difference. I wonder what's the problem

**Comment by ineentho** [comment]
Yea, I maybe should try adding a verbose flag that prints the raw IRC communication. I'll see if I have time for that tonight.

**Comment by ineentho** [comment]
Alright, I've added a `-v` flag that prints all IRC communication. We can hopefully figure out more based on that. In short try:

```
npm i -g mcfm
mcfm -u myUser -o myToken -v
```

**Comment by muazamkamal** [comment]
Thank you for your time. Though when I tried adding the -v flag, it returned with `'-v' expects a value`. Does all of this have anything to do with port usage, eg. certain ports are blocked or something.

**Comment by ineentho** [comment]
That's strange, -v defenitly works for me. Are you sure you updated to the latest version? `npm list -g mcfm` should print 1.0.5.

**Comment by muazamkamal** [comment]
Was not updated to the latest (1.0.5). But the problem still persist. Enter the command line (including -v) still shows as the same as before (nothing happens).

**Comment by ineentho** [comment]
Ok, you do not recieve any response at all from the sever then. I have no clue why that could be, maybe start by trying to connect through a regular IRC client: http://help.twitch.tv/customer/portal/articles/1302780-twitch-irc

**Comment by muazamkamal** [comment]
Alright, it seems that I can't even connect to the twitch IRC. Upon connecting, 

## ` \* Unable to connect to server (Connection timed out)
- Connect retry #1 irc.twitch.tv (6667) (dns pool)`

**Comment by ineentho** [comment]
> Does all of this have anything to do with port usage, eg. certain ports are blocked or something.

Why did you ask that? Are you in some kind of tightly controlled environment? I though it was very uncommon with blocked outgoing connections.

**Comment by muazamkamal** [comment]
Not really, but I just had a hunch regarding that. It seemed that the connection to the server could even be established, I just took a guess.

**Comment by ineentho** [comment]
Alright, I'm closing this for now since it's not really related to the software itself (except insufficient error reporting, so I'm adding an for that #2).

A future version using Websockets would probably not have the same issue.

**Comment by ineentho** [comment]
I believe it is fixed with [v1.0.6](https://github.com/ineentho/mcfm-tools/releases/tag/v1.0.6). I didn't realize Twitch run there IRC server on both port 443 and 6667 for cases just like this.
